wandb_version: 1

MAX_TEST_EPISODE_LEN:
  desc: null
  value: 18000
RECORD_TEST_VIDEOS:
  desc: null
  value: false
RECORD_TRAINING_VIDEOS:
  desc: null
  value: false
TEST_EPISODES:
  desc: null
  value: 10
TEST_MODEL_NAME:
  desc: null
  value: potato
TRAIN_ENV:
  desc: null
  value: MineRLTreechop-v0
TRAIN_MODEL_NAME:
  desc: null
  value: potato
TRAIN_TIMESTEPS:
  desc: null
  value: 1000000
TREECHOP_STEPS:
  desc: null
  value: 2000
_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1630658255
    t:
      1:
      - 1
      4: 3.7.11
      5: 0.12.0
      8:
      - 1
      - 5
